
services:

  db:

    image: mysql:8.0

    restart: always

    environment:

      MYSQL_DATABASE: ats_db

      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

      TZ: Asia/Seoul

    ports:

      - "3306:3306"

    volumes:

      - db_data:/var/lib/mysql

    healthcheck:

      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]

      interval: 10s

      timeout: 5s

      retries: 5



  backend:

    build: ./ATS_Project

    restart: always

    depends_on:

      db:

        condition: service_healthy

    environment:

      - TZ=Asia/Seoul

    env_file:

      - .env

    ports:

      - "8080:8080"

    volumes:

      - ./upload:/app/upload



volumes:

  db_data:

